services:
  glacier_exchange:
    container_name: glacier_exchange
    build: .
    ports:
      - "8080:8080"
    networks:
      ctfnet:
        aliases:
          - web.chal.csaw.io
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 8080 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3

networks:
  ctfnet:
    external: true