
services:
  cryptopwn-server:
    image: llmctf/2022f-pwn-cryptopwn
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      ctfnet:
        aliases:
          - pwn.chal.csaw.io

networks:
  ctfnet:
    external: true
