services:
  robust:
    container_name: robust
    build: ./challenge/
    ports:
      - "1337:1337"
    networks:
      ctfnet:
        aliases:
          - crypt.chal.csaw.io
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 1337 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
    privileged: false
    read_only: true

networks:
  ctfnet:
    external: true
