services:
  web:
    image: llmctf/2023f-msc-vectors_machine:latest
    # build: ./server
    ports:
      - 12312:3001
    networks:
      ctfnet:
        aliases:
          - misc.chal.csaw.io

networks:
  ctfnet:
    external: true
