services:
  web:
    image: llmctf/2018q-pwn-bigboi:latest
    ports:
      - 1436:1436
    networks:
      ctfnet:
        aliases:
          - pwn.chal.csaw.io

networks:
  ctfnet:
    external: true
