services:
  web:
    image: llmctf/2023f-for-ancient_forensics:latest
    # build: ./server
    ports:
      - 5000:5000
    networks:
      ctfnet:
        aliases:
          - forensics.chal.csaw.io

networks:
  ctfnet:
    external: true
