# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.  

# SPDX-License-Identifier: CC-BY-NC-4.0


#
# Example file for setting up django
python: "3.9"
install: "python setup.py install"
pip_packages: ["setuptools"]
