
services:
  Password_Checker:
    image: "llmctf/2021q-pwn-password_checker"
    ports:
      - 5000:5000
    networks:
      ctfnet:
        aliases:
          - pwn.chal.csaw.io
networks:
  ctfnet:
    external: true