
services:
  game-server:
    image: llmctf/2019q-pwn-pop_goes_the_printer:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      ctfnet:
        aliases:
          - pwn.chal.csaw.io
    ports:
      - "28201:28201"

networks:
  ctfnet:
    external: true