services:
  rusty_road:
    image: "llmctf/2017f-rev-rusty_road"
    ports:
      - 8024:8024
    networks:
      ctfnet:
        aliases:
          - rev.chal.csaw.io

networks:
  ctfnet:
    external: true