services:
  ezmaze:
    container_name: ezmaze
    build: ./challenge/
    ports:
      - "9999:9999"
    networks:
      ctfnet:
        aliases:
          - crypto.chal.csaw.io
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 9999 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
    privileged: false
    read_only: true

networks:
  ctfnet:
    external: true