services:
  noisy-crc:
    container_name: noisy-crc
    build:
      context: ./challenge
      dockerfile: Dockerfile
    ports: 
      - "9999:9999"
    networks:
      ctfnet:
        aliases:
          - crypt.chal.csaw.io
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 9999 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3

networks:
  ctfnet:
    external: true