services:
  blog:
    build: ./dist/blog
    container_name: blog
    extra_hosts:
      - "chunky.chals.sekai.team:host-gateway"
    environment:
      - DB=blog.db
      - FLAG=SEKAI{1337}
      - SECRET_KEY=kgDz@W9ks29myrk8NxiIBqntoZ*N4oBX@
      - JWKS_URL_TEMPLATE=http://chunky.chals.sekai.team:8080/{user_id}/.well-known/jwks.json
    networks:
      - ctfnet

  nginx:
    build: ./dist/nginx
    container_name: nginx
    networks:
      - ctfnet

  cache:
    build: ./dist/rcache
    container_name: cache
    ports:
      - "8080:8080"
    networks:
      ctfnet:
        aliases:
          - web.chal.csaw.io

networks:
  ctfnet:
    external: true
