
services:
  game-server:
    image: llmctf/2023f-cry-describeme:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      ctfnet:
        aliases:
          - crypto.chal.csaw.io
    ports:
      - 21200:21200

networks:
  ctfnet:
    external: true