
services:
  game-server:
    image: llmctf/2023q-msc-android_dropper:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      ctfnet:
        aliases:
          - android-dropper.csaw.io
    # ports:
    #   - "3003:3003"

networks:
  ctfnet:
    external: true