
services:
  gift-shop-server:
    image: llmctf/2022q-cry-gift_shop
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      ctfnet:
        aliases:
          - crypto.chal.csaw.io
    ports:
      - 6000:6000

networks:
  ctfnet:
    external: true
