services:
  alice:
    container_name: alice
    build: .
    ports:
      - "1234:1337"
    networks:
      ctfnet:
        aliases:
          - alice.chal.csaw.io
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 1337 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
    environment:
      - USERNAME=alice
    user: 1337:1337
    volumes: 
      - sage_writable_alice:/sage_writable
    cap_add: []
    cap_drop: []

  bob:
    container_name: bob
    build: .
    ports:
      - "1235:1337"
    networks:
      ctfnet:
        aliases:
          - bob.chal.csaw.io
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 1337 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
    environment:
      - USERNAME=bob

networks:
  ctfnet:
    external: true

volumes:
  sage_writable_alice:
