services:
  best_router:
    image: llmctf/2017q-for-best_router
    ports:
      - 80:80
    networks:
      ctfnet:
        aliases:
          - forensics.chal.csaw.io
networks:
  ctfnet:
    external: true
