
services:
  servercontainer:
    image: 'llmctf/2023f-web-triathlon_or_sprint-server'
    build:
      context: ./server
    restart: always
    networks:
      ctfnet:
        aliases:
          - web.chal.csaw.io
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 10s
      timeout: 10s
      retries: 5
# container that adds iptables rules to the subnet to redirect 128.238.66.77 to the servercontainer
  iptables:
    image: 'llmctf/2023f-web-triathlon_or_sprint-iptables'
    build:
      context: ./iptables
    restart: on-failure
    network_mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      servercontainer:
        condition: service_healthy
    privileged: true

networks:
  ctfnet:
    external: true
