services:
  server:
    image: llmctf/2018f-cry-lost_mind
    ports:
      - 32333:32333
    networks:
      ctfnet:
        aliases:
          - crypto.chal.csaw.io

networks:
  ctfnet:
    external: true
